FROM ubuntu:18.04

#RUN apt-get update && \
#    apt-get upgrade -y && \
#    apt-get install -y git && \
#    apt-get install -y iputils-ping && \
#    apt-get install -y net-tools && \
#    apt-get install -y iptables && \
#    apt-get install -y kmod && \
#    apt-get install -y iproute2

# COPY fw2.fw /opt/fw2.fw
# RUN chmod 755 /opt/fw2.fw

# RUN echo "Configurando firewall"

# WORKDIR /opt

# RUN ./fw2.fw    

CMD sleep 100000000000000000000