FROM ubuntu:18.04

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git && \
    apt-get install -y iputils-ping && \
    apt-get install -y net-tools && \
    apt-get install -y curl

CMD sleep 10000000000000000000000